image: Ubuntu  # образ для сборки

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "18"
  
branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - npm install

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования
